### ISSUE TITLE
不能通过线缆直接安装 App

### ISSUE THREAD

**Issue by nlimpid** [wsvn53/twitter-with-shadowsocks#4]
除了开发者账号还需要其他的操作么？

**Comment by wsvn53** [comment]
复制自己正确的 embbed.mobileprovision 进去，iOS Developer 和 iOS Distribute 的分开

**Comment by muyexi** [comment]
根据README重签后，使用PP助手无法通过数据线安装，使用FIR安装后，图标是灰色的，无法正常使用。

**Comment by wsvn53** [comment]
具体错误看看 iOS 日志，根据日志提示来诊断哪里有问题

**Comment by PokerMman** [comment]
cp: /Users/zhsunit/Documents/twitter-with-shadowsocks副本/twitter-fake/Twitter/../../Twitter.app/*: No such file or directory


Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure


 没办法运行
