### ISSUE TITLE
  XCode无法运行

### ISSUE THREAD

**Issue by PokerMman** [wsvn53/twitter-with-shadowsocks#6]
PhaseScriptExecution Copy\ Twitter.app /Users/zhsunit/Library/Developer/Xcode/DerivedData/Twitter-girhoslrjbyysmgcymghcgrqbfpc/Build/Intermediates/Twitter.build/Debug-iphonesimulator/Twitter.build/Script-AA1CDBEB1AA0A19D000AB486.sh
    cd /Users/zhsunit/Documents/twitter/twitter-fake/Twitter
    /bin/sh -c /Users/zhsunit/Library/Developer/Xcode/DerivedData/Twitter-girhoslrjbyysmgcymghcgrqbfpc/Build/Intermediates/Twitter.build/Debug-iphonesimulator/Twitter.build/Script-AA1CDBEB1AA0A19D000AB486.sh

cp: /Users/zhsunit/Documents/twitter/twitter-fake/Twitter/../../Twitter.app/*: No such file or directory
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure

**Comment by wsvn53** [comment]
拉一下最新 repo 代码再试试
