### ISSUE TITLE
线缆安装还是有问题

### ISSUE THREAD

**Issue by PokerMman** [wsvn53/twitter-with-shadowsocks#8]
证书 Provision 设置好 线缆安装还是显示证书有问题
The executable was signed with invalid entitlements.  

网上的所有办法都没用

**Comment by wsvn53** [comment]
这是你 provision 有问题啊，仔细排查一下 xcode 里输出的设备日志，里面有详细的失败原因

**Comment by PokerMman** [comment]
谢谢  是 IClund 没开启
